### ISSUE TITLE
invalid environment on login-open action

### ISSUE THREAD

**Issue by tvquizphd** [tvquizphd/public-quiz-device#75]
ACTION: FAILURE.
Error: Invalid env: DEPLOYMENT
    at toError (/snapshot/public-quiz/dist/index.js:44:28)
    at /snapshot/public-quiz/dist/index.js:199:19
    at Object.<anonymous> (/snapshot/public-quiz/dist/index.js:5[36](https://github.com/tvquizphd/public-quiz/actions/runs/5490388375/jobs/10005755546#step:3:37):3)

**Comment by tvquizphd** [comment]
Closed, now Issue #76
