### ISSUE TITLE
Invalid installation in login-open action

### ISSUE THREAD

**Issue by tvquizphd** [tvquizphd/public-quiz-device#76]
ACTION: FAILURE.
Error: Secret ROOT__INSTALLATION invalid.
    at toInstallation (/snapshot/public-quiz/dist/util/pasted.js:129:15)
    at /snapshot/public-quiz/dist/index.js:348:69
Error: Process completed with exit code 1.

**Comment by tvquizphd** [comment]
Resolved in v6.33.4
